[uwsgi]
  chdir = /home/josh/code/StatusBoard
  module = StatusBoard.wsgi:application
  home = /home/josh/code/StatusBoard/env

  master = true
  processes = 5
  enable-threads = true
  threads = 2

  socket = 0.0.0.0:8000
  vacuum = true
  die-on-term = true

  max-requests = 10000
  harakiri = 20
  protocol      = http