# Generated by Django 5.2.10 on 2026-01-11 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "css",
                    models.CharField(
                        choices=[
                            ("btn-primary", "Primary"),
                            ("btn-secondary", "Secondary"),
                            ("btn-success", "Success"),
                            ("btn-danger", "Danger"),
                            ("btn-warning", "Warning"),
                            ("btn-info", "Infomation"),
                            ("btn-light", "Light"),
                            ("btn-dark", "Dark"),
                            ("btn-link", "Link"),
                        ],
                        max_length=15,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "verbose_name": "Status",
                "verbose_name_plural": "Status",
                "db_table": "status",
            },
        ),
        migrations.CreateModel(
            name="UserStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lock_status", models.BooleanField(default=False)),
                ("lock_notes", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=100)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="StatusApp.status",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "UserStatus",
                "verbose_name_plural": "UserStatus",
                "db_table": "User_status",
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="member_of", to="StatusApp.userstatus"
                    ),
                ),
                (
                    "mods",
                    models.ManyToManyField(
                        blank=True, related_name="moderating", to="StatusApp.userstatus"
                    ),
                ),
            ],
        ),
    ]
