# Generated by Django 5.2.10 on 2026-01-16 10:47

from django.db import migrations


def create_statusapp_group_admins(apps, schema_editor):
    group_model = apps.get_model("auth", "Group")
    permission_model = apps.get_model("auth", "Permission")
    content_type_model = apps.get_model("contenttypes", "ContentType")
    status_group_model = apps.get_model("StatusApp", "Group")

    content_type, _ = content_type_model.objects.get_or_create(
        app_label="StatusApp",
        model="group",
    )
    permissions = []

    for action in ["add", "change", "delete", "view"]:
        codename = f"{action}_group"
        permission, _ = permission_model.objects.get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={
                "name": f"Can {action} {status_group_model._meta.verbose_name}",
            },
        )
        permissions.append(permission)

    group, _ = group_model.objects.get_or_create(name="StatusApp_GroupAdmins")
    group.permissions.set(permissions)


def delete_statusapp_group_admins(apps, schema_editor):
    group_model = apps.get_model("auth", "Group")
    group_model.objects.filter(name="StatusApp_GroupAdmins").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("StatusApp", "0002_default_data"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(
            create_statusapp_group_admins,
            delete_statusapp_group_admins,
        ),
    ]
