# Generated by Django 5.2.10 on 2026-01-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StatusApp", "0003_default_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="external_sync",
            field=models.BooleanField(default=False),
        ),
    ]
